server:
  port: 8082
spring:
  application:
    name: ComplianceService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: compliance
      username: 'mongoadmin'
      password: 'password'
      authentication-database: admin

